game={level:5,players:2,wins:[0,0,0,0],time:0,gaming:1,mission:0,
classicRespawn:false,invis:false}
types={
  wave:[
    [
      [
        ['Pistol',6],
        ['Flamethrower',4],
      ],[
        ['RocketLauncher',3],
        ['Baller',3],
        ['Pistol',4],
      ],[
        ['Tank',1],
        ['Sniper',2],
        ['Spy',2],
      ],[
        ['MachineGun',3],
        ['Pistol',5],
        ['Spy',2],
      ],[
        ['BigMachineGun',1],
        ['Pistol',6],
      ],[
        ['BigCritRocketLauncher',1],
        ['Pistol',4],
        ['Spy',3],
      ],[
        ['Pistol',16],
        ['Sniper',2],
      ],[
        ['Tank',1],
        ['Pistol',4],
        ['BigMachineGun',1],
        ['BigCritRocketLauncher',1],
        ['HyperMedic',1],
      ],
    ],[
      [
        ['Pistol',9],
        ['Flamethrower',6],
        ['MachineGun',5],
      ],[
        ['RocketLauncher',4],
        ['BigCritRocketLauncher',1],
        ['Pistol',10],
        ['Engineer',1],
        ['FastPunch',3],
      ],[
        ['BigFlamethrower',1],
        ['HyperMedic',1],
        ['MachineGun',3],
        ['RocketLauncher',6],
        ['Pistol',2],
        ['PlusMedic',2],
        ['Spy',2],
        ['Sniper',1],
      ],[
        ['Tank',1],
        ['BigBaller',1],
        ['RocketLauncher',4],
        ['Pistol',5],
        ['Engineer',1],
        ['Sniper',2],
      ],[
        ['HeavyPunch',5],
        ['BigMachineGun',1],
        ['Punch',9],
        ['Spy',2],
        ['Engineer',1],
      ],[
        ['RocketLauncher',5],
        ['BigCritRocketLauncher',1],
        ['BigMachineGun',1],
        ['FastMedic',3],
        ['HeavyTank',1]
        ['SpreadSniper',2],
      ],
    ],[
      [
        ['FastPunch',3],
        ['SpreadSniper',3],
        ['BigFastPunch',1],
        ['BigBaller',1],
        ['PlusMedic',2],
      ],[
        ['Tank',1],
        ['RapidPunch',8],
      ],[
        ['BigRapidRocketLauncher',1],
        ['RocketLauncherHeal',3],
        ['FastPunch',3],
        ['PlusMedic',3],
        ['Spy',1],
      ],[
        ['BigFlamethrower',2],
        ['BigFastPistol',4],
      ],[
        ['Pistol',9],
        ['PushPistol',9],
        ['MachineGun',4],
      ],[
        ['HeavyPunch',11],
        ['RapidPunch',6],
        ['RocketLauncherHeal',3],
        ['Tank',2]
      ],
    ],[
      [
        ['Pistol',4],
        ['MachineGun',4],
        ['RocketLauncher',3],
        ['FastPunch',5],
        ['Spy',2],
        ['Engineer',1],
      ],[
        ['HeavyTank',1],
        ['BigMachineGun',2],
        ['RocketLauncherBuff',1],
        ['MachineGun',7],
        ['Pistol',4],
        ['Sniper',2],
        ['Spy',1],
      ],[
        ['BigFastPistol',2],
        ['BigBaller',1],
        ['MachineGun',5],
        ['Baller',4],
        ['Sniper',1],
      ],[
        ['Flamethrower',5],
        ['HyperPistol',6],
        ['CritRocketLauncher',5],
        ['HeavyTank',1],
        ['BigFastPistol',1],
        ['Spy',1],
        ['Engineer',1],
      ],[
        ['Flamethrower',1],
        ['HyperMedic',4],
        ['RocketLauncher',3],
        ['BigDeflectorMachineGun',2],
        ['CritSpreadSniper',3],
        ['Sniper',2],
        ['Engineer',1],
      ],[
        ['CritHyperPistol',5],
        ['MachineGun',2],
        ['Flamethrower',2],
        ['HyperMedic',4],
        ['BigMachineGun',1],
        ['BigCritRapidRocketLauncher',1],
        ['BigMedic',2],
        ['RemoverSniper',2],
      ],[
        ['HeavyTank',2],
        ['HyperMedic',4],
        ['RocketLauncher',2],
        ['BigSpamRocketLauncher',2],
        ['MachineGun',4],
        ['BigBaller',1],
        ['HyperPistol',2],
        ['SpreadSniper',2],
        ['Spy',2],
        ['Engineer',1],
      ],[
        ['PunchBoss',1],
        ['Spy',5],
        ['Sniper',3],
      ],
    ],[
      [
        ['Flamethrower',8],
        ['RapidPunch',4],
        ['BigLongFlamethrower',1],
      ],[
        ['Spy',4],
        ['SpreadSniper',12],
      ],[
        ['BigFastPistol',2],
        ['RocketLauncher',12],
      ],[
        ['Punch',11],
        ['Sniper',2],
        ['Spy',4],
      ],[
        ['BigSpamRocketLauncher',2],
        ['HyperMedic',2],
        ['Baller',7],
        ['RocketLauncher',6],
      ],[
        ['BigCritPushRocketLauncher',2]
        ['HyperMedic',6],
        ['Tank',1],
        ['Sniper',2],
        ['Spy',4],
      ],[
        ['BigFastPistol',2],
        ['RocketLauncherBuff',3],
        ['MachineGun',4],
        ['Baller',4],
        ['Sniper',2],
        ['Pistol',4],
      ],[
        ['Tank',1],
        ['BigMachineGun',3],
        ['BigCritPushRocketLauncher',3],
        ['HyperMedic',6],
        ['MachineGun',3],
        ['Sniper',2],
      ],
    ],[
      [
        ['Pistol',2],
        ['HyperPistol',3],
        ['CritRocketLauncher',1],
        ['BigSpamRocketLauncher',1],
        ['CritMachineGun',1],
        ['HyperMedic',1],
        ['Flamethrower',3],
        ['CritPistol',4],
        ['Sniper',1],
        ['Spy',1],
        ['Engineer',2],
      ],[
        ['SpreadSniper',3],
        ['HeavyTank',1],
        ['BigFastPistol',2],
        ['BigDeflectorMachineGun',1],
        ['BigMedic',1],
        ['RocketLauncher',5],
        ['BigCritPushRocketLauncher',1],
        ['HyperMedic',1],
        ['Engineer',1],
      ],[
        ['Flamethrower',2],
        ['HyperMedic',2],
        ['BigCritRapidRocketLauncher',1],
        ['CritSpreadSniper',3],
        ['BigBaller',3],
        ['CritMachineGun',2],
        ['HyperMedic',2],
        ['Tank',1],
        ['Engineer',1],
        ['Pistol',4],
      ],[
        ['Engineer',1],
        ['CritPistol',8],
        ['HyperMedic',2],
        ['BigMachineGun',2],
        ['Spy',14],
        ['Engineer',1],
      ],[
        ['HeavyPunch',12],
        ['HyperMedic',2],
        ['RemoverSniper',2],
        ['Engineer',1],
        ['CritRocketLauncher',8],
      ],[
        ['BigCritDeflectorMachineGun',1],
        ['BigMedic',1],
        ['BigFastPistol',1],
        ['Tank',1],
        ['HeavyTank',1],
        ['BigSpamRocketLauncher',1],
        ['Sniper',1],
        ['CritRocketLauncher',4],
        ['CritMachineGun',4],
        ['CritFlamethrower',4],
        ['CritPistol',3],
        ['CritBaller',3],
      ],[
        ['RocketLauncherBoss',1],
        ['Spy',5],
        ['Sniper',3],
      ]
    ],[
      [
        ['Punch',20],
        ['Engineer',5],
      ],[
        ['FastPunch',5],
        ['Pistol',3],
        ['PushPistol',3],
        ['BigFastPistol',1],
        ['BigFastPunch',1],
        ['SpreadSniper',3],
        ['PlusMedic',4],
        ['Tank',1],
        ['Engineer',2],
      ],[
        ['Flamethrower',3],
        ['RocketLauncherHeal',4],
        ['HeavyPunch',4],
        ['FastPunch',2],
        ['Engineer',3],
        ['HyperMedic',3],
        ['SpreadSniper',3],
      ],[
        ['Engineer',3],
        ['HyperMedic',3],
        ['Pistol',8],
        ['PushPistol',4],
        ['HyperPistol',4],
        ['BigFastPistol',2],
        ['Sniper',2],
        ['Tank',1],
      ],[
        ['Tank',3],
        ['Pistol',16],
        ['PushPistol',2],
        ['HyperPistol',2],
        ['RocketLauncherHeal',4],
        ['Engineer',2],
        ['HyperMedic',2],
      ],[
        ['BallerBoss',1],
        ['Engineer',7],
        ['Pistol',7],
      ],
    ],[
      [
        ['ShotgunBurst',3],
        ['BigFlipPistol',2],
        ['BigFlamethrower',1],
        ['HyperMedic',4],
        ['SpreadSniper',6],
        ['BigFastPistol',1],
        ['Flamethrower',4],
        ['RocketLauncher',8],
        ['Sniper',2],
        ['Pistol',2],
      ],[
        ['FastPunch',4],
        ['RapidCritSpreadSniper',3],
        ['HyperMedic',5],
        ['Pistol',2],
        ['BigLongCritFlamethrower',1],
        ['Spy',2],
        ['PullPistol',4],
        ['BigDamageOverTimeMachineGun',2],
        ['RocketLauncherHealSelf',8],
        ['BigRocketLauncherHealSelf',1],
      ],[
        ['Shotgun',4],
        ['HyperMedic',6],
        ['Baller',4],
        ['Flamethrower',2],
        ['CritFlamethrower',4],
        ['PullPistol',4],
        ['HyperPistol',5],
        ['EngineerWeak',2],
        ['BigShotgunBurst',2],
        ['BigRadiusRocketLauncher',1],
        ['FastPunchHealSelf',2],
      ],[
        ['MachineGun',2],
        ['FastPunchHealSelf',3],
        ['HyperMedic',3],
        ['Flamethrower',4],
        ['Sniper',2],
        ['BigShotgun',2],
        ['BigSpamCritRocketLauncher',1],        
        ['BigMedic',1],
        ['RapidCritBaller',10],
        ['BigRapidCritBaller',2],
      ],[
        ['BigRocketLauncherHealSelf',1],
        ['CritMachineGun',6],
        ['BigFlipPistol',1],
        ['BigShotgun',4],
        ['CritPushPistol',9],
        ['CritPullPistol',3], 
        ['CritHeavyPunch',2],
        ['RadiusRocketLauncher',5],
        ['BigHyperPistol',2],
        ['Shotgun',4],
        ['Spy',1],
      ],[
        ['RocketLauncherHeal',5],
        ['BigShotgun',2],
        ['CritRocketLauncher',4],
        ['HyperMedic',4],
        ['CritMachineGun',2],
        ['Sniper',2],
        ['Engineer',1],
        ['CritPistol',3],
        ['BigCritDeflectorMachineGun',2],
        ['MachineGunBoss',1],
      ],
    ],
  ],player:[
    {
      name:'PlayerShotgun',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:0,
    },{
      name:'PlayerPistol',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'PlayerMachineGun',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:2,
    },{
      name:'PlayerRocketLauncher',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1.5,crit:0,weapon:3,
    },{
      name:'PlayerSniper',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1.5,crit:0,weapon:6,
    },{
      name:'PlayerBaller',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:7,
    },{
      name:'PlayerFlamethrower',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:8,
    },{
      name:'PlayerEngineer',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1.5,crit:0,weapon:10,
    },{
      name:'PlayerMedic',sizeBuff:1,lifeBuff:3,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:11,
    },
    
    {
      name:'Pistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'MachineGun',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:2,
    },{
      name:'RocketLauncher',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'CritRocketLauncher',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:3,
    },{
      name:'BigCritRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:3,
    },{
      name:'Engineer',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:10,
    },{
      name:'Punch',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:9,
    },{
      name:'RapidPunch',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:2,crit:0,weapon:9,
    },{
      name:'FastPunch',sizeBuff:1,lifeBuff:1,speedBuff:1.2,
      damageBuff:1,reloadBuff:1,crit:0,weapon:9,
    },{
      name:'HeavyPunch',sizeBuff:1,lifeBuff:2,speedBuff:0.6,
      damageBuff:1.5,reloadBuff:1,crit:0,weapon:9,
    },{
      name:'BigRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'Flamethrower',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:8,
    },{
      name:'BigFlamethrower',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:8,
    },{
      name:'Sniper',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:6,
    },{
      name:'Medic',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:11,
    },{
      name:'HyperMedic',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:14,
    },{
      name:'PlusMedic',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:13,
    },{
      name:'Spy',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'Tank',sizeBuff:1.5,lifeBuff:10,speedBuff:0.4,
      damageBuff:1,reloadBuff:1,crit:0,weapon:5,
    },{
      name:'HeavyTank',sizeBuff:1.5,lifeBuff:15,speedBuff:0.4,
      damageBuff:1,reloadBuff:1,crit:0,weapon:5,
    },{
      name:'Baller',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:7,
    },{
      name:'BigBaller',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:7,
    },{
      name:'BigMachineGun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:2,
    },{
      name:'SpreadSniper',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:12,
    },{
      name:'CritSpreadSniper',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:12,
    },{
      name:'BigFastPunch',sizeBuff:2,lifeBuff:5,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:9,
    },{
      name:'BigRapidRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:2,crit:0,weapon:3,
    },{
      name:'RocketLauncherHeal',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'BigPistol',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'BigFastPistol',sizeBuff:2,lifeBuff:3,speedBuff:0.75,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'PushPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:15,
    },{
      name:'RocketLauncherBuff',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'HyperPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'CritHyperPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:1,
    },{
      name:'BigDeflectorMachineGun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:16,
    },{
      name:'BigMedic',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:11,
    },{
      name:'BigCritRapidRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:2,crit:1,weapon:3,
    },{
      name:'RemoverSniper',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:17,
    },{
      name:'BigSpamRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:4,crit:0,weapon:18,
    },{
      name:'PunchBoss',sizeBuff:2.5,lifeBuff:50,speedBuff:1.2,
      damageBuff:2,reloadBuff:2,crit:1,weapon:9,
    },{
      name:'LongFlamethrower',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:19,
    },{
      name:'BigLongFlamethrower',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:19,
    },{
      name:'BigCritPushRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:20,
    },{
      name:'CritPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:1,
    },{
      name:'CritMachineGun',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:2,
    },{
      name:'CritFlamethrower',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:8,
    },{
      name:'CritBaller',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:7,
    },{
      name:'BigCritDeflectorMachineGun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:16,
    },{
      name:'RocketLauncherBoss',sizeBuff:2.5,lifeBuff:50,speedBuff:0.3,
      damageBuff:1,reloadBuff:6,crit:1,weapon:18,
    },{
      name:'BallerBoss',sizeBuff:2.5,lifeBuff:50,speedBuff:0.3,
      damageBuff:1,reloadBuff:3,crit:1,weapon:21,
    },{
      name:'Shotgun',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:0,
    },{
      name:'ShotgunBurst',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:22,
    },{
      name:'BigFlipPistol',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:23,
    },{
      name:'RapidCritSpreadSniper',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:2,crit:1,weapon:12,
    },{
      name:'BigLongCritFlamethrower',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:19,
    },{
      name:'PullPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:24,
    },{
      name:'BigDamageOverTimeMachineGun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:25,
    },{
      name:'RocketLauncherHealSelf',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:26,
    },{
      name:'BigRocketLauncherHealSelf',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:26,
    },{
      name:'EngineerWeak',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:0.6,crit:0,weapon:10,
    },{
      name:'BigShotgunBurst',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:22,
    },{
      name:'RadiusRocketLauncher',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:27,
    },{
      name:'BigRadiusRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:27,
    },{
      name:'BigShotgun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:0,
    },{
      name:'FastPunchHealSelf',sizeBuff:1,lifeBuff:1,speedBuff:1.2,
      damageBuff:1,reloadBuff:1,crit:0,weapon:28,
    },{
      name:'BigSpamCritRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:4,crit:1,weapon:18,
    },{
      name:'RapidCritBaller',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:2,crit:1,weapon:7,
    },{
      name:'BigRapidCritBaller',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:2,crit:1,weapon:7,
    },{
      name:'CritPushPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:15,
    },{
      name:'CritPullPistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:1,weapon:24,
    },{
      name:'CritHeavyPunch',sizeBuff:1,lifeBuff:2,speedBuff:0.6,
      damageBuff:1.5,reloadBuff:1,crit:1,weapon:9,
    },{
      name:'BigHyperPistol',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'BigCritDeflectorMachineGun',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:16,
    },{
      name:'MachineGunBoss',sizeBuff:2.5,lifeBuff:50,speedBuff:0.3,
      damageBuff:1.5,reloadBuff:1.5,crit:1,weapon:29,
    },
  ],weapon:[
		{
			name:'Shotgun',
			ammo:2,
			damage:20,
			cooldown:30,
			stop:60,
			reload:20,
			speed:1.15,
      uses:12,
		},{
			name:'Pistol',
			ammo:10,
			damage:45,
			cooldown:12,
			stop:30,
			reload:10,
			speed:1.4,
      uses:30,
		},{
			name:'Machine Gun',
			ammo:30,
			damage:20,
			cooldown:4,
			stop:120,
			reload:3,
			speed:0.9,
      uses:120,
		},{
			name:'Rocket Launcher',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Assault Rifle',
			ammo:18,
			damage:25,
			cooldown:20,
			stop:90,
			reload:5,
			speed:1.1,
      uses:54,
		},{
			name:'Kamikaze',
			ammo:1,
			damage:200,
			cooldown:999,
			stop:999,
			reload:999,
			speed:1.5,
      uses:1,
		},{
			name:'Sniper',
			ammo:1,
			damage:105,
			cooldown:120,
			stop:120,
			reload:120,
			speed:0.85,
      uses:4,
		},{
			name:'Baller',
			ammo:3,
			damage:60,
			cooldown:30,
			stop:120,
			reload:20,
			speed:1.05,
      uses:9,
		},
    
    {
			name:'Flamethrower',
			ammo:50,
			damage:25,
			cooldown:3,
			stop:75,
			reload:2,
			speed:0.95,
      uses:100,
		},{
			name:'Punch',
			ammo:1,
			damage:60,
			cooldown:15,
			stop:15,
			reload:15,
			speed:1.35,
      uses:40,
		},{
			name:'Engineer',
			ammo:1,
			damage:60,
			cooldown:240,
			stop:240,
			reload:240,
			speed:0.975,
      uses:5,
		},{
			name:'Medic',
			ammo:10,
			damage:20,
			cooldown:10,
			stop:30,
			reload:8,
			speed:1.2,
      uses:30,
		},{
			name:'Spread Sniper',
			ammo:1,
			damage:105,
			cooldown:120,
			stop:120,
			reload:120,
			speed:0.85,
      uses:4
		},{
			name:'Plus Medic',
			ammo:10,
			damage:20,
			cooldown:10,
			stop:30,
			reload:8,
			speed:1.2,
      uses:30,
		},{
			name:'Hyper Medic',
			ammo:10,
			damage:20,
			cooldown:10,
			stop:30,
			reload:8,
			speed:1.2,
      uses:10,
		},{
			name:'Push Pistol',
			ammo:10,
			damage:45,
			cooldown:12,
			stop:30,
			reload:10,
			speed:1.4,
      uses:30,
		},{
			name:'Deflector Machine Gun',
			ammo:30,
			damage:20,
			cooldown:4,
			stop:120,
			reload:3,
			speed:0.9,
      uses:120,
		},{
			name:'Remover Sniper',
			ammo:1,
			damage:105,
			cooldown:120,
			stop:120,
			reload:120,
			speed:0.85,
      uses:4,
		},{
			name:'Spam Rocket Launcher',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Long Flamethrower',
			ammo:50,
			damage:25,
			cooldown:3,
			stop:75,
			reload:2,
			speed:0.95,
      uses:100,
		},{
			name:'Push Rocket Launcher',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Spray Baller',
			ammo:3,
			damage:60,
			cooldown:30,
			stop:120,
			reload:20,
			speed:1.05,
      uses:9,
		},{
			name:'Shotgun Burst',
			ammo:4,
			damage:20,
			cooldown:15,
			stop:90,
			reload:15,
			speed:1.15,
      uses:12,
		},{
			name:'Flip Pistol',
			ammo:10,
			damage:45,
			cooldown:12,
			stop:30,
			reload:10,
			speed:1.4,
      uses:30,
		},{
			name:'Pull Pistol',
			ammo:10,
			damage:45,
			cooldown:12,
			stop:30,
			reload:10,
			speed:1.4,
      uses:30,
		},{
			name:'Damage Over Time Machine Gun',
			ammo:30,
			damage:20,
			cooldown:4,
			stop:120,
			reload:3,
			speed:0.9,
      uses:120,
		},{
			name:'Rocket Launcher Heal Self',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Rocket Launcher Radius',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Punch Heal Self',
			ammo:1,
			damage:60,
			cooldown:15,
			stop:15,
			reload:15,
			speed:1.35,
      uses:40,
		},{
			name:'Machine Gun Heal Self',
			ammo:30,
			damage:20,
			cooldown:4,
			stop:120,
			reload:3,
			speed:0.9,
      uses:120,
		},
	],
}
stage={scene:'main'}
display={wave:0,anim:0,cycle:0,wait:120}
graphics={main:[]}
entities={projectiles:[],players:[],walls:[]}
run={fore:[],info:[],back:[]}
inputs={keys:[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]}
transition={trigger:false,anim:0,scene:stage.scene}
levels=[
    [
        "############     ###",
        "        5         6 ",
        " 7 #         # #    ",
        "   # ## ###### #### ",
        " ### ## #     8     ",
        "                     ",
        "## ######  # ##### #",
        "      4 #### #    1 ",
        "  ##            #   ",
        " #### # ### ## #####",
        "  ##  #   #  #     #",
        "      #      #   # #",
        "#   # ## ### #   #  ",
        "    #  #     #####  ",
        "    ## #  #        #",
        "    #     #  ##    #",
        "###   ### ####   ###",
        "# 2            3 #  ",
        "#    #   #   #   #  ",
        "##################  ",
    ],[
				"          7         ",
				"                    ",
        "         ###        ",
        "                    ",
        "#    ###    ###    #",
        "#  5  ##     #   6 #",
        "#     ##     #     #",
        "## ######## #### ###",
        "#  ##   # 8 ###  ###",
        "#   # # #   ###  ###",
        "#     #   ######   #",
        "## #### #    #   # #",
        "#       ## #   ### #",
        "# 2 ###### ## ## 3 #",
        "#   ###   4 #  #   #",
        "# ###   #   #  # ###",
        "#  ## ####### ##   #",
        "## #   # 1 #   ### #",
        "#  # # #   # # #   #",
        "#    #   #   #   ###",
        "####################",
		],[
				"####################",
        "#     #     #       ",
        "#     #     #       ",
        "#  3  #  #  #  4  # ",
        "#        #        # ",
        "#        #        # ",
        "##### ##### ##### # ",
        "#     #           # ",
        "#     #           # ",
        "#           #     # ",
        "#           #     # ",
        "#     #     #     # ",
        "#### ### ##### #### ",
        "#                 # ",
        "#                 # ",
        "#   #       #     # ",
        "#   #       #       ",
        "#   #       #       ",
        "# ##### ######### ##",
        "#           #     # ",
        "#           #     # ",
        "# #####           # ",
        "#     #             ",
        "#     #     #       ",
        "#### ###### # ##### ",
        "#     #     #     # ",
        "#           #     # ",
        "#  2        #  1  # ",
        "#     #     #     # ",
        "#     #     #     # ",
        "# ##### ######## ## ",
        "#     #           # ",
        "#     #           # ",
        "#     #      #    # ",
        "#            #      ",
        "#        #   #      ",
        "####################",
		],[
			"####################",
        " 1   #              ",
        "   #                ",
        " ###        #####  #",
        "                    ",
        "      # #           ",
        "##  # ### # #  2  # ",
        "                    ",
        "               #    ",
        "  ##                ",
        "       #   #    ## #",
        "               ##   ",
        " #  #               ",
        "              ##### ",
        "  3    ###          ",
        "               4    ",
        " ###     ###      # ",
        " #             # ## ",
        " #                  ",
        " ###   #  #  #######",
		],[
      "###############################################",
      "#                            #               ##",
      "#     #      #       8       #               ##",
      "##           #              ###   6  ###      #",
      "####  5  ### #####  ####               #      #",
      "#                   #            ##    #####  #",
      "#     #             #  #####   ######     #   #",
      "#   #####    ########  #            ##    #   #",
      "#       ##             #                     ##",
      "#    4   ##            ###   #                #",
      "#         ##    #      #    ###           2   #",
      "#  # ##    ######## #      ## ##    ###       #",
      "#  #                #          ##    #    #####",
      "#  #  #             ##   ##  7  ##   #   ##   #",
      "# #########   ###  ##     ##         #        #",
      "#            ## ## #       ## ##   ###        #",
      "#           ##              ###      ###     ##",
      "##  #  #   ##         ####   #       #      ###",
      "#         ##    ###      #       #         ####",
      "#        ####     #      #       #          ###",
      "###   ######      ##     ## #######          ##",
			"#         #        #                  #       #",
      "#         #   ##   #   #              #       #",
      "#   ###   #       ##       #  #    ######     #",
      "#    #    #       #        #  #     #         #",
      "#    #          ###  ##  ### ####   #     #   #",
      "# ####               #     #  #     #    #### #",
      "#    #######         #     #  #     #    #    #",
      "##      #  ##        ##  #### ###   ###  #    #",
      "#       #       #          #  #             ###",
      "#  3           ####        #  #            1  #",
      "#         #             #          #  ##      #",
      "####      #                        #          #",
      "#     #####    #######      ##    ###     ##  #",
			"#   ###   ##  ##     ##   #####  ##########   #",
      "#                          ##                 #",
      "#       #                                     #",
      "###     #           #             ###        ##",
			"###############################################",
    ],[
      "                                                                  #",
      "                                                               5  #",
      "                                                                  #",
      "                                                    ##      ####  #",
      "                                                            #     #",
      "                                                            #     #",
      "                                                  ###########  ####",
      "                                                      #           #",
      "                                                               6  #",
      "                                              ######              #",
      "                                              #    #  ##########  #",
      "                                  #        ####            #      #",
      "                                  #        #               #      #",
      "                                  ####     #    ########## #      #", 
      "                                  #        #  ###                 #",
      "                                  #        #                 ######",
      "                                ###   #### #                      #",
      "                        #####                       #     #       #",
      "                            #                    ###### #######  ##",
      "                            #   #     #                     #     #",
      "                   #######  #  #########     #                  7 #",
      "                   #                   #  ###############         #",
      "                                       #                        ###",
      "                      ###############  #                      #####",
      "                       #          #           #  ###########    ###",
      "                  ##   #          #           #       #           #",
      "          ###     #                      ###  #                   #",
      "          #       #         #            #    ####                #",
      "      #   #    ######    ############### #            #########   #",
      "  #####                                               #     #     #",
      "  #   #                                         #######     #   ###",
      "    3             ####  #   ##########                            #",
      "           4  #         #   #        #                            #",
      "##  #####     #         #   #        ############         #########",
      "#       #  ######  # ####  ##  ###         #               #      #",
      "#   2         1    #                                ###        8  #",
      "#                  #               #   #           #####          #",
      "###################################################################",
    ]
]