game={level:5,players:4,wins:[0,0,0,0],time:0,gaming:1,mission:0}
types={
  wave:[
    [
      [
        ['Pistol',9],
        ['Flamethrower',6],
        ['MachineGun',5],
      ],[
        ['RocketLauncher',4],
        ['BigCritRocketLauncher',1],
        ['Pistol',10],
        ['Engineer',1],
        ['PunchSpeed',3],
      ]
    ],
  ],player:[
    {
      name:'PlayerShotgun',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:0,
    },{
      name:'PlayerPistol',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'PlayerMachineGun',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:2,
    },{
      name:'PlayerRocketLauncher',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'PlayerSniper',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:6,
    },{
      name:'PlayerBaller',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:7,
    },{
      name:'PlayerFlamethrower',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:8,
    },{
      name:'PlayerEngineer',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:10,
    },{
      name:'PlayerMedic',sizeBuff:1,lifeBuff:2,speedBuff:1,
      damageBuff:1,reloadBuff:1,crit:0,weapon:11,
    },
    
    {
      name:'Pistol',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:1,
    },{
      name:'Flamethrower',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:8,
    },{
      name:'MachineGun',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:2,
    },{
      name:'RocketLauncher',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:3,
    },{
      name:'BigCritRocketLauncher',sizeBuff:2,lifeBuff:5,speedBuff:0.3,
      damageBuff:1,reloadBuff:1,crit:1,weapon:3,
    },{
      name:'Engineer',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:10,
    },{
      name:'Punch',sizeBuff:1,lifeBuff:1,speedBuff:0.6,
      damageBuff:1,reloadBuff:1,crit:0,weapon:10,
    },{
      name:'PunchSpeed',sizeBuff:1,lifeBuff:1,speedBuff:1.2,
      damageBuff:1,reloadBuff:1,crit:0,weapon:10,
    },
  ],weapon:[
		{
			name:'Shotgun',
			ammo:2,
			damage:20,
			cooldown:30,
			stop:60,
			reload:20,
			speed:1.15,
      uses:12,
		},{
			name:'Pistol',
			ammo:10,
			damage:45,
			cooldown:12,
			stop:30,
			reload:10,
			speed:1.4,
      uses:30,
		},{
			name:'Machine Gun',
			ammo:30,
			damage:20,
			cooldown:4,
			stop:120,
			reload:3,
			speed:0.9,
      uses:120,
		},{
			name:'Rocket Launcher',
			ammo:1,
			damage:150,
			cooldown:20,
			stop:180,
			reload:0,
			speed:0.8,
      uses:3,
		},{
			name:'Assault Rifle',
			ammo:18,
			damage:25,
			cooldown:20,
			stop:90,
			reload:5,
			speed:1.1,
      uses:54,
		},{
			name:'Kamikaze',
			ammo:1,
			damage:200,
			cooldown:999,
			stop:999,
			reload:999,
			speed:1.5,
      uses:1,
		},{
			name:'Sniper',
			ammo:1,
			damage:105,
			cooldown:120,
			stop:120,
			reload:120,
			speed:0.85,
      uses:4,
		},{
			name:'Baller',
			ammo:3,
			damage:60,
			cooldown:30,
			stop:120,
			reload:20,
			speed:1.05,
      uses:9,
		},
    
    {
			name:'Flamethrower',
			ammo:50,
			damage:25,
			cooldown:3,
			stop:75,
			reload:2,
			speed:0.95,
      uses:100,
		},{
			name:'Punch',
			ammo:1,
			damage:60,
			cooldown:15,
			stop:15,
			reload:15,
			speed:1.35,
      uses:40,
		},{
			name:'Engineer',
			ammo:1,
			damage:60,
			cooldown:240,
			stop:240,
			reload:240,
			speed:0.975,
      uses:5,
		},{
			name:'Medic',
			ammo:10,
			damage:20,
			cooldown:10,
			stop:30,
			reload:8,
			speed:1.2,
      uses:30,
		},
	],
}
stage={scene:'main'}
display={wave:0,anim:0,cycle:0,wait:120}
graphics={main:[]}
entities={projectiles:[],players:[],walls:[]}
run={fore:[],info:[],back:[]}
inputs={keys:[[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]]}
transition={trigger:false,anim:0,scene:stage.scene}
levels=[
    [
        "############     ###",
        "                    ",
        " 4 #         # #    ",
        "   # ## ###### #### ",
        " ### ## #           ",
        "                    ",
        "## ######  # ##### #",
        "        #### #    1 ",
        "  ##            #   ",
        " #### # ### ## #####",
        "  ##  #   #  #     #",
        "      #      #   # #",
        "#   # ## ### #   #  ",
        "    #  #     #####  ",
        " 2  ## #  #        #",
        "    #     #  ##    #",
        "###   ### ####   ###",
        "#              3 #  ",
        "#    #   #   #   #  ",
        "####### ### ######  ",
    ],[
				"          4         ",
				"                    ",
        "      2  ###  3     ",
        "                    ",
        "#    ###    ###    #",
        "#     ##     #     #",
        "#     ##     #     #",
        "## ######## #### ###",
        "#  ##   #   ###  ###",
        "#   # # #   ###  ###",
        "#     #   ######   #",
        "## #### #    #   # #",
        "#       ## #   ### #",
        "#   ###### ## ##   #",
        "#   ###     #  #   #",
        "# ###   #   #  # ###",
        "#  ## ####### ##   #",
        "## #   # 1 #   ### #",
        "#  # # #   # # #   #",
        "#    #   #   #   ###",
        "####################",
		],[
				"####################",
        "#     #     #       ",
        "#     #     #       ",
        "#  3  #  #  #  4  # ",
        "#        #        # ",
        "#        #        # ",
        "##### ##### ##### # ",
        "#     #           # ",
        "#     #           # ",
        "#           #     # ",
        "#           #     # ",
        "#     #     #     # ",
        "#### ### ##### #### ",
        "#                 # ",
        "#                 # ",
        "#   #       #     # ",
        "#   #       #       ",
        "#   #       #       ",
        "# ##### ######### ##",
        "#           #     # ",
        "#           #     # ",
        "# #####           # ",
        "#     #             ",
        "#     #     #       ",
        "#### ###### # ##### ",
        "#     #     #     # ",
        "#           #     # ",
        "#  2        #  1  # ",
        "#     #     #     # ",
        "#     #     #     # ",
        "# ##### ######## ## ",
        "#     #           # ",
        "#     #           # ",
        "#     #      #    # ",
        "#            #      ",
        "#        #   #      ",
        "####################",
		],[
			"####################",
        " 1   #              ",
        "   #                ",
        " ###        #####  #",
        "                    ",
        "      # #           ",
        "##  # ### # #  2  # ",
        "                    ",
        "               #    ",
        "  ##                ",
        "       #   #    ## #",
        "               ##   ",
        " #  #               ",
        "              ##### ",
        "  3    ###          ",
        "               4    ",
        " ###     ###      # ",
        " #             # ## ",
        " #                  ",
        " ###   #  #  #######",
		],[
      "###############################################",
      "#                            #               ##",
      "#     #      #               #               ##",
      "##           #              ###      ###      #",
      "####     ### #####  ####               #      #",
      "#                   #            ##    #####  #",
      "#     #             #  #####   ######     #   #",
      "#   #####    ########  #            ##    #   #",
      "#       ##             #                     ##",
      "#    4   ##            ###   #                #",
      "#         ##    #      #    ###           2   #",
      "#  # ##    ######## #      ## ##    ###       #",
      "#  #                #          ##    #    #####",
      "#  #  #             ##   ##     ##   #   ##   #",
      "# #########   ###  ##     ##         #        #",
      "#            ## ## #       ## ##   ###        #",
      "#           ##              ###      ###     ##",
      "##  #  #   ##         ####   #       #      ###",
      "#         ##    ###      #       #         ####",
      "#        ####     #      #       #          ###",
      "###   ######      ##     ## #######          ##",
			"#         #        #                  #       #",
      "#         #   ##   #   #              #       #",
      "#   ###   #       ##       #  #    ######     #",
      "#    #    #       #        #  #     #         #",
      "#    #          ###  ##  ### ####   #     #   #",
      "# ####               #     #  #     #    #### #",
      "#    #######         #     #  #     #    #    #",
      "##      #  ##        ##  #### ###   ###  #    #",
      "#       #       #          #  #             ###",
      "#  3           ####        #  #            1  #",
      "#         #             #          #  ##      #",
      "####      #                        #          #",
      "#     #####    #######      ##    ###     ##  #",
			"#   ###   ##  ##     ##   #####  ##########   #",
      "#                          ##                 #",
      "#       #                                     #",
      "###     #           #             ###        ##",
			"###############################################",
    ],[
      "                                                                  #",
      "                                                               5  #",
      "                                                                  #",
      "                                                    ##      ####  #",
      "                                                            #     #",
      "                                                            #     #",
      "                                                  ###########  ####",
      "                                                      #           #",
      "                                                               6  #",
      "                                              ######              #",
      "                                              #    #  ##########  #",
      "                                  #        ####            #      #",
      "                                  #        #               #      #",
      "                                  ####     #    ########## #      #", 
      "                                  #        #  ###                 #",
      "                                  #        #                 ######",
      "                                ###   #### #                      #",
      "                        #####                       #     #       #",
      "                            #                    ###### #######  #",
      "                            #   #     #                           #",
      "                   #######  #  #########                        7 #",
      "                   #                   #  ##################      #",
      "                                       #                        ###",
      "                      ###############  #                      #####",
      "                       #          #           #  ###########    ###",
      "                  ##   #          #           #       #           #",
      "          ###     #                      ###  #                   #",
      "      #           #         #            #    ####                #",
      "      #        ######    #################            #########   #",
      "  #####                                               #     #     #",
      "  #   #                                          ######     #   ###",
      "    3               ####### ##########                            #",
      "           4  #             #        #                            #",
      "##  #####     #             #        ############         #########",
      "#       #  ######  #    ##### ####         #         #     #      #",
      "#   2         1    #                                ###        8  #",
      "#                  #               #   #           #####          #",
      "###################################################################",
    ]
]